
name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: surge ./ https://mi-pagina-web-TU-USUARIO.surge.sh --token ${{ secrets.SURGE_TOKEN }}
